const themes = {
    dark: {
        "--bg-color": "#121212",
        "--sidebar-color": "#1e1e1e",
        "--accent-color": "#007acc",
        "--text-color": "#e0e0e0",
        "--text-dim": "#888888",
        "--border-color": "#333333",
        "--card-bg": "#1e1e1e",
        "--input-bg": "#161616",
        "--hover-color": "#2d2d30",
        "--shadow-color": "rgba(0,0,0,0.5)",
        "--border-radius": "6px",
        "--font-family": "'Segoe UI', system-ui, sans-serif",
        "--transition-speed": "0.2s",
        "--danger-color": "#ff6b6b",
        "--danger-border": "#5a2a2a",
        "--header-color": "#ffffff",
        "--success-color": "#28a745",
        "--warning-color": "#ffc107"
    },
    light: {
        "--bg-color": "#f0f2f5",
        "--sidebar-color": "#ffffff",
        "--accent-color": "#0078d4",
        "--text-color": "#333333",
        "--text-dim": "#666666",
        "--border-color": "#e1e4e8",
        "--card-bg": "#ffffff",
        "--input-bg": "#f9f9f9",
        "--hover-color": "#e1e4e8",
        "--shadow-color": "rgba(0,0,0,0.1)",
        "--border-radius": "6px",
        "--font-family": "'Segoe UI', system-ui, sans-serif",
        "--transition-speed": "0.2s",
        "--danger-color": "#d9534f",
        "--danger-border": "#e1e4e8",
        "--header-color": "#333333",
        "--success-color": "#28a745",
        "--warning-color": "#ffc107"
    },
    oled: {
        "--bg-color": "#000000",
        "--sidebar-color": "#000000",
        "--accent-color": "#ff4400",
        "--text-color": "#ffffff",
        "--text-dim": "#a0a0a0",
        "--border-color": "#333333",
        "--card-bg": "#111111",
        "--input-bg": "#000000",
        "--hover-color": "#222222",
        "--shadow-color": "rgba(255, 68, 0, 0.1)",
        "--border-radius": "0px",
        "--font-family": "Consolas, monospace",
        "--transition-speed": "0s",
        "--danger-color": "#ff4444",
        "--danger-border": "#550000",
        "--header-color": "#ffffff",
        "--success-color": "#00ff00",
        "--warning-color": "#ffff00"
    },
    cyberpunk: {
        "--bg-color": "#0b0b19",
        "--sidebar-color": "#121226",
        "--accent-color": "#fceE0a", 
        "--text-color": "#00ff9f",
        "--text-dim": "#05d9e8",
        "--border-color": "#ff2a6d",
        "--card-bg": "#121226",
        "--input-bg": "#050514",
        "--hover-color": "#2a2a40",
        "--shadow-color": "rgba(255, 42, 109, 0.4)",
        "--border-radius": "2px",
        "--font-family": "'Orbitron', sans-serif",
        "--transition-speed": "0.1s",
        "--danger-color": "#ff2a6d",
        "--danger-border": "#ff2a6d",
        "--header-color": "#fceE0a",
        "--success-color": "#00ff9f",
        "--warning-color": "#fceE0a"
    },
    dracula: {
        "--bg-color": "#282a36",
        "--sidebar-color": "#44475a",
        "--accent-color": "#bd93f9",
        "--text-color": "#f8f8f2",
        "--text-dim": "#6272a4",
        "--border-color": "#6272a4",
        "--card-bg": "#44475a",
        "--input-bg": "#282a36",
        "--hover-color": "#6272a4",
        "--shadow-color": "rgba(0,0,0,0.3)",
        "--border-radius": "8px",
        "--font-family": "'Fira Code', monospace",
        "--transition-speed": "0.3s",
        "--danger-color": "#ff5555",
        "--danger-border": "#ff5555",
        "--header-color": "#f8f8f2",
        "--success-color": "#50fa7b",
        "--warning-color": "#f1fa8c"
    },
    neon_city: {
        "--bg-color": "#050505",
        "--sidebar-color": "#0a0a0a",
        "--accent-color": "#00ff00",
        "--text-color": "#ffffff",
        "--text-dim": "#ff00ff",
        "--border-color": "#00ff00",
        "--card-bg": "#0a0a0a",
        "--input-bg": "#000000",
        "--hover-color": "#111111",
        "--shadow-color": "rgba(0, 255, 0, 0.3)",
        "--border-radius": "12px",
        "--font-family": "'Courier New', monospace",
        "--transition-speed": "0.4s",
        "--danger-color": "#ff0000",
        "--danger-border": "#ff0000",
        "--header-color": "#00ff00",
        "--success-color": "#00ff00",
        "--warning-color": "#ffff00"
    },
    midnight: {
        "--bg-color": "#0f172a",
        "--sidebar-color": "#1e293b",
        "--accent-color": "#38bdf8",
        "--text-color": "#f1f5f9",
        "--text-dim": "#94a3b8",
        "--border-color": "#334155",
        "--card-bg": "#1e293b",
        "--input-bg": "#0f172a",
        "--hover-color": "#334155",
        "--shadow-color": "rgba(0,0,0,0.6)",
        "--border-radius": "8px",
        "--font-family": "'Inter', sans-serif",
        "--transition-speed": "0.25s",
        "--danger-color": "#ef4444",
        "--danger-border": "#991b1b",
        "--header-color": "#f1f5f9",
        "--success-color": "#22c55e",
        "--warning-color": "#f59e0b"
    },
    forest: {
        "--bg-color": "#1a2f1a",
        "--sidebar-color": "#254025",
        "--accent-color": "#4caf50",
        "--text-color": "#e8f5e9",
        "--text-dim": "#a5d6a7",
        "--border-color": "#388e3c",
        "--card-bg": "#254025",
        "--input-bg": "#1b331b",
        "--hover-color": "#2e522e",
        "--shadow-color": "rgba(0,0,0,0.4)",
        "--border-radius": "10px",
        "--font-family": "'Segoe UI', sans-serif",
        "--transition-speed": "0.3s",
        "--danger-color": "#e57373",
        "--danger-border": "#d32f2f",
        "--header-color": "#e8f5e9",
        "--success-color": "#81c784",
        "--warning-color": "#ffd54f"
    },
    ocean: {
        "--bg-color": "#001f3f",
        "--sidebar-color": "#003366",
        "--accent-color": "#0074D9",
        "--text-color": "#DDDDDD",
        "--text-dim": "#AAAAAA",
        "--border-color": "#0074D9",
        "--card-bg": "#003366",
        "--input-bg": "#001a35",
        "--hover-color": "#004080",
        "--shadow-color": "rgba(0, 116, 217, 0.3)",
        "--border-radius": "15px",
        "--font-family": "Verdana, sans-serif",
        "--transition-speed": "0.5s",
        "--danger-color": "#FF4136",
        "--danger-border": "#85144b",
        "--header-color": "#DDDDDD",
        "--success-color": "#2ECC40",
        "--warning-color": "#FFDC00"
    },
    sunset: {
        "--bg-color": "#2d1b2e",
        "--sidebar-color": "#45283c",
        "--accent-color": "#ff9a8b",
        "--text-color": "#ffecd2",
        "--text-dim": "#b08ea2",
        "--border-color": "#ff6b6b",
        "--card-bg": "#45283c",
        "--input-bg": "#2d1b2e",
        "--hover-color": "#5e3650",
        "--shadow-color": "rgba(255, 107, 107, 0.3)",
        "--border-radius": "20px",
        "--font-family": "'Trebuchet MS', sans-serif",
        "--transition-speed": "0.4s",
        "--danger-color": "#ff6b6b",
        "--danger-border": "#c92a2a",
        "--header-color": "#ffecd2",
        "--success-color": "#51cf66",
        "--warning-color": "#fcc419"
    },
    high_contrast: {
        "--bg-color": "#000000",
        "--sidebar-color": "#000000",
        "--accent-color": "#ffff00",
        "--text-color": "#ffffff",
        "--text-dim": "#ffffff",
        "--border-color": "#ffffff",
        "--card-bg": "#000000",
        "--input-bg": "#000000",
        "--hover-color": "#333333",
        "--shadow-color": "none",
        "--border-radius": "0px",
        "--font-family": "Arial, sans-serif",
        "--transition-speed": "0s",
        "--danger-color": "#ff0000",
        "--danger-border": "#ffffff",
        "--header-color": "#ffffff",
        "--success-color": "#00ff00",
        "--warning-color": "#ffff00"
    },
    retro: {
        "--bg-color": "#fdf6e3",
        "--sidebar-color": "#eee8d5",
        "--accent-color": "#cb4b16",
        "--text-color": "#657b83",
        "--text-dim": "#93a1a1",
        "--border-color": "#b58900",
        "--card-bg": "#eee8d5",
        "--input-bg": "#fdf6e3",
        "--hover-color": "#d3cbb8",
        "--shadow-color": "rgba(0,0,0,0.2)",
        "--border-radius": "4px",
        "--font-family": "'Press Start 2P', cursive",
        "--transition-speed": "0s",
        "--danger-color": "#dc322f",
        "--danger-border": "#b58900",
        "--header-color": "#657b83",
        "--success-color": "#859900",
        "--warning-color": "#b58900"
    },
    coffee: {
        "--bg-color": "#2b211e",
        "--sidebar-color": "#3e302b",
        "--accent-color": "#d4a373",
        "--text-color": "#f3e5dc",
        "--text-dim": "#a4907c",
        "--border-color": "#6f4e37",
        "--card-bg": "#3e302b",
        "--input-bg": "#261c19",
        "--hover-color": "#4e3d38",
        "--shadow-color": "rgba(0,0,0,0.5)",
        "--border-radius": "8px",
        "--font-family": "Georgia, serif",
        "--transition-speed": "0.3s",
        "--danger-color": "#d45d5d",
        "--danger-border": "#8a4b3d",
        "--header-color": "#f3e5dc",
        "--success-color": "#8ba88e",
        "--warning-color": "#d4a373"
    },
    nord: {
        "--bg-color": "#2e3440",
        "--sidebar-color": "#3b4252",
        "--accent-color": "#88c0d0",
        "--text-color": "#d8dee9",
        "--text-dim": "#4c566a",
        "--border-color": "#4c566a",
        "--card-bg": "#3b4252",
        "--input-bg": "#2e3440",
        "--hover-color": "#434c5e",
        "--shadow-color": "rgba(0,0,0,0.2)",
        "--border-radius": "5px",
        "--font-family": "'Rubik', sans-serif",
        "--transition-speed": "0.2s",
        "--danger-color": "#bf616a",
        "--danger-border": "#4c566a",
        "--header-color": "#d8dee9",
        "--success-color": "#a3be8c",
        "--warning-color": "#ebcb8b"
    }
};

module.exports = themes;